name: build
on:
  push:
    branches:
      - '**'
  create_release:
    name: 'create_release'
    runs-on: ubuntu-latest
    steps:
      - uses: marvinpinto/action-automatic-releases@v1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{ github.event.pull_request.title }}
