name: Create release tag and release note.
on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    name: 'deploy'
    if: ${{ endWith(github.ref, 'main') }}
    runs-on: ubuntu-last
    steps:
      - name: 'echo'
        run: |
          echo 'hoge'
