name: Create release tag and release note.
on:
  push:
    branches:
      - '**'
jobs:
  deploy:
    name: 'deploy'
    if: ${{ endsWith(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'echo'
        run: |
          today=$(date +'%Y.%m.%d')
          echo $today
  create-release-tag:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # 前回のリリースタグを取得する
      - name: 'Get previous tag'
        id: previous_tag
        run: >
          echo "previous_tag=$(curl -H 'Accept: application/vnd.github.v3+json' -H
          'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
          https://api.github.com/repos/${{ github.repository }}/releases/latest
          | jq -r .tag_name)" >> $GITHUB_OUTPUT
      # タグを生成する 「{YYYY.MM.DD}-{当日リリース回数}」
      - name: 'Generate release tag'
        id: release_tag
        run: |
          today=$(date +'%Y.%m.%d')
          pre_release_date=$(echo ${{ steps.previous_tag.outputs.previous_tag }} | awk -F'-' '{print $1}')
          pre_release_count=$(echo ${{ steps.previous_tag.outputs.previous_tag }} | awk -F'-' '{print $2}')
          if [[ ! $pre_release_date = $today ]]; then
            echo "init count"
            pre_release_count=0
          fi
          echo "release_tag=$today-$(($pre_release_count + 1))" >> $GITHUB_OUTPUT
      # 前回リリースからの差分をもとに、リリースノートの本文を生成する
      - name: 'Generate release note'
        id: release_note
        run: >
          echo "release_note=$(
          curl -X POST -H 'Accept: application/vnd.github.v3+json'
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
          https://api.github.com/repos/${{ github.repository }}/releases/generate-notes
          -d '{"tag_name":"${{ steps.release_tag.outputs.release_tag }}",
          "previous_tag_name":"${{ steps.previous_tag.outputs.previous_tag }}"}'
          | jq .body | sed 's/^"//' | sed 's/"$//' | sed 's/\"//g')">> $GITHUB_OUTPUT
      - name: 'Create Release'
        run: >
          curl -X POST
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          -d "{ \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\",
          \"name\": \"${{ steps.release_tag.outputs.release_tag }}\",
          \"body\": \"${{ steps.release_note.outputs.release_note }}\"}"
          https://api.github.com/repos/${{ github.repository }}/releases
