name: Create release tag and release note.
on:
  workflow_run:
    workflows: [test]
    types: [completed]
jobs:
  main:
    name: main
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))
